### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by Sogl** [dudeonthehorse/Email#10]
Привет!

Опишу последовательность действий, в результате которых возникла ошибка:
1. Установил `gulp` глобально через `npm i -g gulp` 
2. Создал папку `email-dev`, перешел в неё
3. Склонировал ветку `dev` через команду `git clone https://github.com/dudeonthehorse/Email.git -b dev .`
4. Запустил `npm install`, все модули установились без проблем
5. В этой же папке запустил `gulp` и получил такой вывод `[10:53:26] No gulpfile found`

Я так понимаю, именно в `guplfile` должны быть описаны все tasks и watchers, но он попросту отсуствует =)

**Comment by dudeonthehorse** [comment]
Привет. Gulp необязательно устанавливать глобально - npm install его сам подтянет.
Запускать gulp необходимо в папке проекта. Для каждого отдельного проекта. Пока так. Дальше видно будет.

**Comment by Sogl** [comment]
Ок, понял. Перешел в `projects/mainProject`, запустил `gulp` и получил такой output:

```
[11:13:15] Using gulpfile c:\projects\email-dev\projects\mainProject\gulpfile.js
[11:13:15] Starting 'default'...
[11:13:15] Starting 'concatcss'...
[11:13:15] Finished 'concatcss' after 24 ms
[11:13:15] Starting 'inliner'...
[11:13:15] Starting 'images'...
[11:13:15] Finished 'inliner' after 213 ms
[11:13:15] Finished 'images' after 331 ms
[11:13:15] Starting 'watch'...
[11:13:15] Finished 'watch' after 325 ms
[11:13:15] Finished 'default' after
```

Все сработало как нужно, в папке `build` получил готовый проект.
Такой вопрос... чтобы стартовать новый проект в `projects`, какой минимальный набор файлов необходим? Везде копировать `mainProject`?

**Comment by dudeonthehorse** [comment]
Все верно. mainProject - это демопроект с минимальным набором. В папке проекта может быть сколько угодно шаблонов, но все они завязаны на общем css файле. Предлагаю изучить конфиг в папке gulpCommonTasks, для общего понимания работы сборщика. Там все достаточно очевидно.
