### ISSUE TITLE
Проблемы с отображением в outlook web app

### ISSUE THREAD

**Issue by Sogl** [dudeonthehorse/Email#13]
Привет!

В OWA шаблон тестировался? Я сегодня зашел туда и обнаружил вот такое отображение кнопки, которая по идее должна быть по центру:
![image](https://cloud.githubusercontent.com/assets/7556290/10605359/a6cd8f6a-7765-11e5-9e3c-3a1d2aab061d.png)

**Comment by dudeonthehorse** [comment]
OWA - это office 365? Да, мне говорили, что там есть небольшие проблемы. Надо будет потестировать его.

**Comment by Sogl** [comment]
> OWA - это office 365?

Не совсем. Это компонент для веб-доступа к корпоративной почте, который входит в состав Exchange. 

Версия нашего сервера:
![image](https://cloud.githubusercontent.com/assets/7556290/10655427/e4cc3412-78b7-11e5-8106-85a10a3805d2.png)
В консоли версия указана так: `
 Version 14.2 (Build 247.5)`

> Надо будет потестировать его.

Могу оказать посильную помощь в тестировании =)

**Comment by Sogl** [comment]
Вопрос с кнопкой снимается. 

Оказывается, по умолчанию в OWA включен режим отображения сообщений в виде бесед (как в gmail-почте). Именно из-за этого шаблон разъезжается в разные стороны. При переключении на режим отдельных писем все выглядит вполне достойно.

**Comment by dudeonthehorse** [comment]
"Могу оказать посильную помощь в тестировании =)" - ну как я могу тут отказать :)
Насколько мне известно, 365 игнорирует max-width и при этом не понимает outlook conditional comments
