### ISSUE TITLE
LESS и SASS 

### ISSUE THREAD

**Issue by pafnuty** [dudeonthehorse/Email#14]
Не планируется ли добавление LESS и SASS для более удобной сборки?

**Comment by dudeonthehorse** [comment]
Пока нет. В обозримом будущем будут новые шаблоны, структуризация подключаемых областей, шаблонизатор с переменными и массивами, сниппеты для элементов и еще пара плюшек.

**Comment by pafnuty** [comment]
Но никто же не будет против, если я попробую добавить less? 
В свете будущих планов это было бы актуально, всё же проще, чем голый css писать :)

**Comment by dudeonthehorse** [comment]
Без проблем

**Comment by pafnuty** [comment]
Первая попытка: https://github.com/dudeonthehorse/Email/pull/15
