### ISSUE TITLE
Special tags

### ISSUE THREAD

**Issue by nosovk** [dudeonthehorse/Email#19]
Hello!
I use your template for building SendGrid templates.
There is <% text %> wrapper for their special tags (like <%asm_group_unsubscribe_url%> )
But somehow gulp build fails in that tag. I know that it's invalid, that's why I try to add ignore regexp to html parser.

[projects/gulpCommonTasks/tasks/inliner.js](https://github.com/dudeonthehorse/Email/blob/dev/gulpCommonTasks/tasks/inliner.js)
`.pipe(htmlmin({collapseWhitespace: true, minifyCSS: true, ignoreCustomFragments:"/\<\%[\sa-z_]+\%\>/ig"}))`

but htmlmin still try to minify that tag and fails.
Any ideas how to fix that?

**Comment by dudeonthehorse** [comment]
Hello!
Really, it's a minifier bug. The simplest way to resolve this problem - not using minifier in your templates. Ha-ha!
Looks like your problem https://github.com/kangax/html-minifier/issues/462
I'm not strong in regular expressions and I can't help you with it.
