### ISSUE TITLE
Изображение смещается при изменении размера окна

### ISSUE THREAD

**Issue by baribadamshin** [dudeonthehorse/Email#22]
![2016-03-05 4 10 37](https://cloud.githubusercontent.com/assets/478811/13544548/3e86459e-e288-11e5-98f3-1f015b586302.png)

Привет!
На макоси, в стандартной программе Почта, во время изменения размера окна, изображение смещается влево (с лого в шапке все окей, я просто убрал центрирование).

Не могу понять почему это происходит :(

**Comment by dudeonthehorse** [comment]
Привет. Проблему повторить не смог. El Capitan, Apple Mail 9.2

**Comment by baribadamshin** [comment]
Жаль, ну ладно, возможно мне удастся выявить причину или сценарий при котором это происходит
