### ISSUE TITLE
Парсер Yandex (web, android) неправильно обрабатывает кнопку  "Try Inliner"

### ISSUE THREAD

**Issue by maksim-shabanski** [dudeonthehorse/Email#3]
Привет!
При тестировании обнаружил, что парсер yandex не так, как хотелось бы, обрабатывает кнопку "Try Inliner". И в итоге кнопка становится полностью не кликабельная.

**Comment by dudeonthehorse** [comment]
Привет, спасибо за внимательность. Буквально вчера отловил эту багу. Аналогичная ситуация происходит и в Mailbox(OSX, iOS) и Airmail(OSX).

Только что сделал апдейт с новой вариацией реализации кнопки. Во всех нормальных почтовиках она более, чем вменяема. В аутлуке выглядит более компактно. На данный момент считаю такое поведение нормальным компромиссом. В дальнейшем планирую сделать для нее костыль в виде условных комментариев для аутлука.
