### ISSUE TITLE
Awquard question.

### ISSUE THREAD

**Issue by jdc20181** [dudeonthehorse/Email#31]
What is this for exactly? How could I use it for a project soon to be coming up? Could this be used with my own in-application Mailer for bugs?

How can I help you? Any "issues" I can look at??

**Comment by dudeonthehorse** [comment]
I call it "Bootstrap for email newsletters". But u can use it only like a email template.

**Comment by jdc20181** [comment]
Thanks! Anything I could help with?

**Comment by dudeonthehorse** [comment]
No, I don't need help right now. Thx.
