### ISSUE TITLE
Неверное имя шаблона в projects/kilogram

### ISSUE THREAD

**Issue by ilyasamorodov** [dudeonthehorse/Email#32]
При старте сервера через gulp шаблон с именем simple.html не подхватывается и в браузер выводится "Cannot GET /".
Возможно, стоит переименовать его обратно в index.html

**Comment by dudeonthehorse** [comment]
Верно, спасибо, займусь. По уму, неплохо бы на индексной странице выводить ссылки на все собранные в билде письма.

**Comment by dudeonthehorse** [comment]
В текущей версии на индексной странице выводится список писем проекта
