### ISSUE TITLE
Типограф ломает код

### ISSUE THREAD

**Issue by dkanster** [dudeonthehorse/Email#34]
До:
`{% if forloop.revcounter   <= 2 %}`

После:
`{% if&#160;forloop.revcounter &#8804; 2=&#171;&#187; %}=&#171;&#187;`

**Comment by dkanster** [comment]
Предлагаю всё что внутри `{% raw %}...{% endraw %}` не обрабатывать типографом

**Comment by dudeonthehorse** [comment]
До решения проблемы предлагаю не пользоваться типографом.

**Comment by binjospookie** [comment]
А каким образом можно повторить данную проблему?
Я обновил типограф до версии 2.0.1, раскомментировал его в таске и добавил в код 

``` {% if forloop.revcounter <= 2 %} {% endif %}```

Никакой проблемы, связанной с типографом я не увидел.
Осмелюсь предположить, что я просто не повторяю кейс. В противном случае — обновление типографа решает проблему.

**Comment by dudeonthehorse** [comment]
Типограф вообще скользкая тема и требует досконального тестирования. Обязательно доберусь и потестирую.

**Comment by binjospookie** [comment]
Заметил интересный момент. Типограф влияет на номер телефона, например.
Т.е. если взять 
```
<a href="tel:12345678901">+1-234-567-89-01</a>
```
, то `+1-234-567-89-01` будет преобразован в `+1 (234) 567-89-01`

**Comment by dudeonthehorse** [comment]
Не сказал бы что это плохо

**Comment by binjospookie** [comment]
Это просто интересный нюанс :)

**Comment by dudeonthehorse** [comment]
Обновился. попробовал, ничего не ломает :)
