### ISSUE TITLE
Не работает :(

### ISSUE THREAD

**Issue by binjospookie** [dudeonthehorse/Email#37]
Сделал `npm install`, перешёл в директорию проекта (`./projects/kilogram_alpha/`), вызвал `gulp` и сразу же словил ошибку:

```
/home/binjo/Документы/kilogram-dev/node_modules/.store/accord@0.23.0/_/lib/adapter_base.js:103
        throw new Error("'tried to require: " + this.supportedEngines + "'.\nNone found. Make sure one has been installed!");
        ^

Error: 'tried to require: less'.
None found. Make sure one has been installed!
```

Node: 6.7.0; Npm: 3.10.3

**Comment by binjospookie** [comment]
Взял себе эту версию и всё ок:
https://github.com/dudeonthehorse/kilogram/tree/1b59fe289a40ff6fa5be641d2ed670fcfd8a47ab

**upd**
https://github.com/dudeonthehorse/kilogram/commit/6d899670e82005b22dc677906a5de87de9506920
до вот этого коммита всё ок, дальше пока ещё не успел посмотреть

**Comment by dudeonthehorse** [comment]
Css файлы в проекте должны быть в .less разширении и ошибки не будет

**Comment by binjospookie** [comment]
Окей, просто это произошло со скаченным архивом ветки. Спасибо)

**Comment by dudeonthehorse** [comment]
https://github.com/dudeonthehorse/kilogram/commit/fab50d89a9eac3eb0c1a484565569976f88fec7c

Поправил

**Comment by binjospookie** [comment]
Спасибо!
