### ISSUE TITLE
Подключение шрифтов

### ISSUE THREAD

**Issue by LanKing** [dudeonthehorse/Email#46]
Подключаю шрифт через link, в билде его нет. В чём соль?

**Comment by dudeonthehorse** [comment]
Привет

В файле ```gulpCommonTasks/tasks/template.js``` необходимо установить значение ```false``` для параметра ```removeLinkTags```

Не исключено, что в текущей реализации шаблона, это нарушит инлайн кода. В ближайшем апдейте я оптимизирую этот момент.

**Comment by LanKing** [comment]
Спасибо, IT Works ;-)
