### ISSUE TITLE
Вырезка неиспользуемых классов

### ISSUE THREAD

**Issue by LanKing** [dudeonthehorse/Email#49]
Можно ли, после того как классы заинлайнились, вырезать их их параметра class для минификации кода?

**Comment by dudeonthehorse** [comment]
Нужно установить значение ```true``` для параметра ```removeHtmlSelectors``` в ```pipe(inlineCss())```

**Comment by dudeonthehorse** [comment]
Документация по возможностям инлайнера здесь https://github.com/jonkemp/inline-css
