### ISSUE TITLE
font-face

### ISSUE THREAD

**Issue by LanKing** [dudeonthehorse/Email#50]
Как сделать, чтобы font-face не вырезался. 
Поясню, подключение шрифтов через link тег -- матерится pagespeed, 
поэтому я захожу на урл линка и копирую содержимое. 
Однако оно нещадно убивается клинером.

**Comment by dudeonthehorse** [comment]
Пока что без шаманства не обойтись по той простой причине, что разные сендеры по разному относятся к подключению шрифтов. А так — можно использовать как ```@import```, так и ```link``` подключение. Оставлю issue открытой для нормальной реализации в сборщике.

**Comment by LanKing** [comment]
Мм, речь о том, что хочется не импорт и не линк, а вставлять фонт фейсы непосредственно в цсс

Или не будет работать в некоторых сендерах? Можно пруф? :)

**Comment by dudeonthehorse** [comment]
Надо тестировать. У каждого сендера на уровне отправки письма стоит свой валидатор. Через font-face не пробовал.

**Comment by dudeonthehorse** [comment]
Универсального решения нет. У каждого сендера действительно свои правила. Кто-то хавает font-face, кто-то только link. Поэтому нет смысла зашивать поддержку на уровне разработки.

Попробуй импортировать font-face версию в мейлчимп, увидишь проблему. Там работает только link-метод.
