### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by zemabishkek** [dudeonthehorse/Email#54]
Прошерстил все комменты вдоль и поперек, не нашел решения, не смог воспользоваться kilogram. Печаль...

**Comment by dudeonthehorse** [comment]
Релиз с документацией в процессе.

**Comment by kizoso** [comment]
Очень ждём!

**Comment by SufferingOnion** [comment]
> Релиз с документацией в процессе.

Все еще очень ждем!) Спасибо большое за классный инструмент, надеюсь вы его не забросили
