### ISSUE TITLE
Может стоит переписать на интернациональный манер документацию? По-английски?

### ISSUE THREAD

**Issue by dderg** [dudeonthehorse/Email#7]

**Comment by dudeonthehorse** [comment]
Моя родная - все же русский язык и сейчас апдейты происходят достаточно часто. Как только дойдем до более стабильной версии, конечно же оформлю на английском.

**Comment by dderg** [comment]
скажешь когда - помогу перевести =)

**Comment by dderg** [comment]
Забавно конечно что gulp воспринимается как волшебство =)

**Comment by dudeonthehorse** [comment]
Это уже неуместный софизм :)

Хорошо.
